version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  front:
    container_name: telite_front
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./app/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.backend=front"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:telite.quixada.ufc.br"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
    networks:
      - internal
      - web

  telite_back:
    container_name: telite_back
    build: .
    image: telite:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: teliteDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./backend/strapi/config:/opt/app/config
      - ./backend/strapi/src:/opt/app/src
      - ./backend/strapi/package.json:/opt/package.json
      - ./backend/strapi/package-lock.json:/opt/package-lock.json       
      #- ./backend/strapi/yarn.lock:/opt/yarn.lock
      - ./backend/strapi/.env:/opt/app/.env
      - ./backend/strapi/public/uploads:/opt/app/public/uploads
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.backend=back"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:telite.quixada.ufc.br; PathPrefixStrip: /strapi"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.default.protocol=http"
    networks:
      - internal
      - web
    depends_on:
      - teliteDB
    #ports:
    #  - '8080:1337'      

  teliteDB:
    container_name: teliteDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - /opt/sistemas/telite/data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5550:5432'
    networks:
      - internal
      - web
